In [46]:
import pandas as pd
import statistics
import math
df = pd.read_csv('influence.csv',index_col=0)

In [47]:
df

            node  ks  kdeg     pr     m
0       17116707  99   194   67.0  3212
1       28465635  99   576  165.0  5380
2      380580781  99   260   85.0  5099
3       18996905  99   668  420.0  4204
4      221036078  84    98   20.0  3058
5      153460275  55    61   41.0  2298
6      107830991  99   234   68.0  5187
7       17868918  99   625  407.0  3373
8      151338729  99   393  135.0  3455
9      222261763  99   322   57.0  7089
10      19705747  81   160   79.0  2595
11      34428380  99  1381  751.0  4694
12      88323281  99   838  174.0  3940
13      19933035  67    71   13.0  3096
14     149538028  99   420  101.0  3484
15     158419434  99   458  107.0  7456
16      17434613  68   101   42.0  2565
17     153226312  99   470   92.0  4796
18     364971269  59    70   14.0  4083
19     100581193  99   297   36.0  5204
20     279787626  99   373   32.0  5334
21     113058991  99   337   46.0  5967
22      69592091  99   394  136.0  5389
23     187773078  99   445  137.0  3847
24     406628822  99   229   35.0  3503
25     262802533  79    82   19.0  3132
26     460282402  59    76   19.0  2966
27     280935165  99   444  102.0  3446
28     437804658  62    62   14.0  2606
29      27633075  99   632  317.0  2688
...          ...  ..   ...    ...   ...
40621  109716962   5     5   11.0    14
40622   14254518   8    13   23.0    93
40623   14230389   4     6   27.0    11
40624   17560697   2     2   14.0    11
40625   16910315   4     6   29.0    11
40626    5820642   1     1    5.0    21
40627   14615785   4     4   15.0     1
40628  105030602   4     4   13.0    11
40629   45425277   2     2   10.0     1
40630   16116713  42    46   28.0  3894
40631   17961886  22    23   29.0  1747
40632   22506222  28    29   14.0  3546
40633   15170346  44    58   33.0  4218
40634   21783950  44    60   26.0  6075
40635  130954892  32    42    6.0  4605
40636   16878156  43    49   33.0  4158
40637  114885308   3     3    6.0   205
40638  117148684   4     4    6.0  1233
40639   21014087  23    27   12.0  3617
40640   84869572   5     5    5.0  1206
40641   65734517   9    13   15.0  3242
40642   52731258   3     3    6.0  1197
40643   16950937   7     9    6.0  1207
40644   17627361  18    24    8.0  3327
40645   12296312   7     7    8.0  4930
40646   19840539  13    13    6.0  3747
40647   62832547   2     2    5.0   205
40648   35108007   6     6    6.0  4869
40649   17221548   5     5    5.0  2286
40650   56799076   1     1    6.0     1

[40651 rows x 5 columns]

In [48]:
df = df.sort_values(by=['pr'], ascending=False)

In [49]:
df = df.sort_values(by=['pr'], ascending=False)
df = df.reset_index(drop=True)

In [56]:
m = max(df['pr'])

In [57]:
div = m//10

In [67]:
bin1 = []
bin2 = []
bin3 = []
bin4 = []
bin5 = []

In [66]:
list1 = unique(df['kdeg'])

In [59]:
for i in range(len(df)):
    ks = df['pr'][i]
    if ks >= div*5 and ks < div*6:
        bin1.append(df['m'][i])
    elif ks >= div*6 and ks < div*7:
        bin2.append(df['m'][i])
    elif ks >= div*7 and ks < div*8:
        bin3.append(df['m'][i])
    elif ks >= div*8 and ks < div*9:
        bin4.append(df['m'][i])
    elif ks >= div*9:
        bin5.append(df['m'][i])

In [60]:
a=sum(bin5)/len(bin5)

In [61]:
b=sum(bin4)/len(bin4)

ZeroDivisionError: division by zero

In [41]:
c=sum(bin3)/len(bin3)

In [42]:
d=sum(bin2)/len(bin2)

In [43]:
e=sum(bin1)/len(bin1)

In [44]:
#list1 = a,b,c,d,e
#list2 = a,b,c,d,e
list3 = a,b,c,d,e

In [45]:
list2

(23915.0, 12102.5, 4432.0, 10102.4, 13085.0)

In [64]:
def unique(list1): 
      
    # insert the list to the set 
    list_set = set(list1) 
    # convert the set to the list 
    unique_list = (list(list_set)) 
    return unique_list

In [65]:
list1 = unique(df['kdeg'])

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 2309,
 262,
 263,
 264,
 261,
 266,
 267,
 268,
 269,
 270,
 271,
 265,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 316,
 317,
 318,
 319,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 347,
 348,
 349,
 350,
 352,
 353,
 354,
 355,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 369,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 380,
 382,
 384,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 396,
 397,
 399,
 400,
 402,
 403,
 404,
 407,
 409,
 410,
 411,
 412,
 414,
 415,
 417,
 418,
 419,
 420,
 421,
 423,
 424,
 426,
 431,
 432,
 433,
 435,
 438,
 440,
 441,
 442,
 444,
 445,
 447,
 450,
 451,
 452,
 453,
 454,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 467,
 470,
 472,
 474,
 475,
 476,
 477,
 480,
 482,
 488,
 490,
 491,
 493,
 497,
 503,
 509,
 510,
 513,
 520,
 521,
 522,
 523,
 525,
 527,
 529,
 532,
 533,
 535,
 537,
 541,
 545,
 547,
 548,
 553,
 557,
 559,
 560,
 562,
 563,
 570,
 574,
 575,
 576,
 580,
 583,
 586,
 595,
 596,
 597,
 600,
 601,
 604,
 607,
 608,
 612,
 615,
 616,
 619,
 620,
 625,
 629,
 632,
 633,
 637,
 641,
 645,
 649,
 651,
 653,
 660,
 662,
 667,
 668,
 670,
 683,
 685,
 686,
 687,
 691,
 724,
 748,
 750,
 771,
 772,
 774,
 777,
 787,
 818,
 826,
 834,
 838,
 841,
 843,
 855,
 858,
 861,
 863,
 875,
 906,
 931,
 944,
 960,
 982,
 1007,
 1084,
 1110,
 1139,
 1256,
 272,
 1372,
 1381,
 1391,
 1462,
 1527,
 1766,
 1874,
 1969]